// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmmvrvsjdeauiphdmrwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtbXZydnNqZGVhdWlwaGRtcnd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjYwMzMsImV4cCI6MjA2ODk0MjAzM30.eCHxMr2CYjE1xxEUMzyAiWyfCE0yVKj5Au_vsReA28Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});